***
# 01: Introduction & Slicing
<br>

`numpy`, a library, creates special python lists called arrays.
<br>
This chapter also includes slicing such arrays, which are different from slicing regular Python.
<br>
Note: To read multidimensional code, go from outer dimension to inner dimension. The last number should be the length of the base list.
***
## Introduction

In [86]:
x = [1,2,3,4,5]
y = [True, 'apple', 41, '2']

These are normal lists, objects built into base Python.<br>
Lists like these can contain multiple datatypes. Because of this, it has its pros and cons.
1. These lists involve greater memory allocation to accommodate to a potential change in datatype. Hence, even if they may all contain integers, it would still require additional memory.
2. In base Python, it is hard to navigate through multidimensional lists (lists in lists).

In [89]:
import numpy as np #convention

In [91]:
#numpy -> numeric python

In numpy, its arrays have the datatype `ndarray` -- short for n-dimensional array. <br><br>
To create an array,

In [94]:
np1 = np.array([0,1,2,3,4])
print(np1)
print(np1[0])

[0 1 2 3 4]
0


The main value of numpy is that it converts `lists` (Python) into `ndarrays` which are more easily and efficiently operated on.

### Function 1: arange()
<br>
Works like Python's range(), similarly having 3 arguments (start, stop, step)<br>

In [31]:
np2 = np.arange(1,10,2)
print(np2)

[1 3 5 7 9]


### Function 2: zeros()
<br>
Creates an array of 0s

In [37]:
np3 = np.zeros(5)
print(np3)

[0. 0. 0. 0. 0.]


This function can also be used to create a **multi-dimensional array**, using a unique notation.

In [46]:
np3_2d = np.zeros((3, 5)) #number of lists, length of list. similar to breadth x length.
print(np3_2d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [48]:
np3_3d = np.zeros((2, 3, 5)) #the number of digits indicates how many dimensions there are
print(np3_3d)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


### Function 3: full()
<br>
Creates an array of n.<br>
Similar multidimensional logic applies. The filled number is a separate argument from the tuple.

In [54]:
np4 = np.full((2,3,4), 1)
print(np4)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


***
## Slicing

For a one-dimensional array, it is similar to Python's slicer

In [81]:
np5 = np.array([0,1,2,3,4,5,6,7,8])
#to get 2-5,
print(np5[2:6])
#to get 0-4,
print(np5[:5])
#to get 3-6 using negative slices,
print(np5[-6:-2])
#to get every even number,
print(np5[::2])
#to get 6-3 (reverse), note: recall step -1 starts on -1 instead of 0
print(np5[-3:-7:-1])
#in the context of slicing, its useful to put another same list beside the list on a number line (not reflected), 
#then simply count backwards until the start of the left list

[2 3 4 5]
[0 1 2 3 4]
[3 4 5 6]
[0 2 4 6 8]
[6 5 4 3]


For multi-dimensional arrays,

In [102]:
np6 = np.array([[1,2,3,4],[5,6,7,8]]) #2d array, 2 rows and 4 columns
print(np6)

[[1 2 3 4]
 [5 6 7 8]]


First, indexing. Let's say we want to pull out the number 7.<br>
It is at the **2nd row, 3rd column**.<br>
Note that in Python, indexing starts at `0`.<br>
In numpy, indexing starts from the outer most shell to the inner most (base) shell.

In [108]:
print(np6[1, 2]) #not to be confused with creation of a two-dimensional array

7


Now, let's start slicing. <br>
Based on the previous line, it is as intuitive. Rather than indicating just a number, indicate a range to slice the array. <br>
Let's say we want to pull 2, 3, 6, 7. <br>
We start by selecting both rows, then the second and third object in these rows. <br>

In [125]:
print(np6[:, 1:3]) #or 0:, :2, 0:2, ... (yes, the ellipsis)

[[2 3]
 [6 7]]


Note above, that the array isnt edited **in place**. It makes a copy that is the desired slice, while the original remains unchanged.
***

### Additional Notes:
- An ellipsis (...) in numpy allows selecting in multiple dimensions at once, that is, it is a full slice [:] for all dimensions it is placed at.
- Can think of it as a [:] but for multiple dimensions at once. This makes it useful for arrays with many dimensions.

Take a 3-dimensional array, 4x4x4. Try visualising

In [134]:
np7 = np.reshape([i for i in range(1, 65)], [4,4,4])
print(np7)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]


Let's say we want to get the right hand side integers for each 2d array.
<br>
Normally, we would input `np7[:,:,3]`, which would work.

In [143]:
print(np7[:,:,3])

[[ 4  8 12 16]
 [20 24 28 32]
 [36 40 44 48]
 [52 56 60 64]]


However, for large n-dimensional arrays, it is often hard to keep track of the number of : to place.
<br>
Therefore, the ellipsis is used to represent an undefined number of :, up to the point where a specific index is indicated.

In [147]:
print(np7[...,3])

[[ 4  8 12 16]
 [20 24 28 32]
 [36 40 44 48]
 [52 56 60 64]]


In [149]:
print(np7[0,...,3])

[ 4  8 12 16]
