***
# 02: Universal Functions
<br>

This chapter contains a bulk of the functions used to manipulate `ndarrays`

In [8]:
import numpy as np

***
#### Function 1: sqrt

In [35]:
np1 = np.reshape([1,4,9,16], [2,2])
print(np1)
print(np.sqrt(np1)) #evidently, it works on n-dimensional arrays as well

[[ 1  4]
 [ 9 16]]
[[1. 2.]
 [3. 4.]]


***
#### Function 2: absolute

In [38]:
np2 = np.reshape([-2,-1,0,1], [2,2])
print(np2)
print(np.absolute(np2))

[[-2 -1]
 [ 0  1]]
[[2 1]
 [0 1]]


***
#### Function 3: exp (for Exponential)
Substitutes each integer into e^x, then returns the result as output

In [47]:
print(np.exp(np2))

[[0.13533528 0.36787944]
 [1.         2.71828183]]


***
#### Function 4: min/max

In [50]:
print(np.max(np2), np.min(np2))

1 -2


***
#### Function 5: sign
Returns -1 for each negative value, 1 for positive value

In [57]:
print(np.sign(np2))

[[-1 -1]
 [ 0  1]]


***
#### Function 6: sin, cos, tan
Applies trigonometry functions to each element

In [60]:
np3 = np.array([1, 0, -1])
print(np.sin(np3))
print(np.cos(np3))
print(np.tan(np3))

[ 0.84147098  0.         -0.84147098]
[0.54030231 1.         0.54030231]
[ 1.55740772  0.         -1.55740772]


***
There are all of the typical mathematical functions for `ndarrays`.
<br>
For more, check out __https://numpy.org/devdocs/reference/ufuncs.html__