***
# 03: Shaping Arrays
<br>
Touch briefly on a copy, vs viewing of an array.
<br>
After which, how to use np.shape and np.reshape.

***

## Copying vs Viewing

In [11]:
import numpy as np
np1 = np.array([0,1,2,3,4,5])
np2 = np1.view()
print(np2)

[0 1 2 3 4 5]


Here, `np2` is set as a 'view' version of `np1`. That is, it opens up `np1` itself to return a value.

In [14]:
np1[0] = 2
print(np2)

[2 1 2 3 4 5]


Hence, `np2` itself is changed when something is done to `np1`, since a view copies the original upon call.

In [17]:
np3 = np1.copy()
print(np3)

[2 1 2 3 4 5]


Here, `np3` is set as a 'copy'. This only copies `np1` once, at the object's creation. After which it is considered a different object altogether from `np1`.

In [20]:
np1[0] = 5
print(np3)

[2 1 2 3 4 5]


Hence, `np3` remains unchanged even with changes made to `np1`.

In [23]:
np3[0] = 100
print(np1)

[5 1 2 3 4 5]


Likewise, `np1` is unchanged.
<br>
Something worth noting is that, when the view is changed (`np2`), the original (`np1`) will be changed as well.

***
## Shaping and Reshaping

#### Function 1: shape
<br>
This function returns the dimensions of any given array. Note it does not change the array.

In [29]:
np1 = np.array([1,2,3,4,5])
np2 = np.array([[1,2,3],[4,5,6]])
print(np1.shape) #1 row, length of 5 (columns). the 1 is omitted
print(np2.shape) #2 rows, length of 3

(5,)
(2, 3)


#### Function 2: reshape
<br>
This function 'molds' the array into another defined shape/dimension.

In [33]:
print(np2.reshape(3,2))
np3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np3.reshape(4,3))

[[1 2]
 [3 4]
 [5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


This function works for n-dimensional arrays as well.

In [39]:
print(np3.reshape(2,2,3))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


This function also has a unique use, in that it can be used to flatten functions.
<br>
Flattening means transforming the function into a uniform, 1-dimensional array that keeps all objects.

In [49]:
np4 = (np.array([i for i in range(1, 17)]).reshape(4,4))
print(np4)
print(np4.reshape(-1)) #flatten - -1

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
