***
# 04: Iterating and Sorting
<br>

`numpy` has its unique way of iteration and sorting, providing easier options to manipulate arrays.

In [6]:
import numpy as np

***
## Iteration

#### 1-D 

In [12]:
np1 = np.array([1,2,3,4,5,6])
for i in np1: 
    print(i) #simple, as with lists

1
2
3
4
5
6


#### 2-D

In [16]:
np2 = np1.reshape(2,3)
for i in np2:
    print(i)

[1 2 3]
[4 5 6]


This simply returns the (n-1)th dimension in the form of a series.
<br>
But what if the intended output was the individual objects? Certainly, we could nest loops.

In [24]:
for i in np2:
    for num in i:
        print(num)

1
2
3
4
5
6


But for large n-dimensional arrays, this may not be so easy. 
- For individual integers, this can be done easily by flattening the array.

In [27]:
for i in np2.reshape(-1):
    print(i)

1
2
3
4
5
6


#### nditer

Even simpler, `numpy` has its own dedicated iterator, `np.nditer`.

In [31]:
for i in np.nditer(np2):
    print(i)

1
2
3
4
5
6


***
## Sorting
<br>

`numpy` has its own `sort` function as well.

#### 1-D

In [42]:
np3 = np.array([6,3,7,1,5,4,8])
print(np.sort(np3))
print(np3)

np4 = np.array(['John', 'Bob', 'Alice'])
print(np.sort(np4))
print(np4)

np5 = np.array([True, False, True, False])
print(np.sort(np5))
print(np5)

[1 3 4 5 6 7 8]
[6 3 7 1 5 4 8]
['Alice' 'Bob' 'John']
['John' 'Bob' 'Alice']
[False False  True  True]
[ True False  True False]


It is important to note that `.sort` only creates a temporary copy (unless assigned) at the moment it is called. It does not change the original array.

#### 2-D

In [46]:
np6 = np.array([[7,3,9,0], [1,4,8,2]])
print(np.sort(np6))

[[0 3 7 9]
 [1 2 4 8]]


For multidimensional arrays, `.sort` sorts within the group.