***
# 05: Searching & Filtering

***
## Searching

In [4]:
import numpy as np

In [8]:
np1 = np.array([1,2,3,4,5,6,2])
print(np.where(np1 == 2))

(array([1, 6], dtype=int64),)


To obtain indexes (for whatever reason), just quote [0] of this search function.

In [13]:
search = np.where(np1 == 2)
print(search[0]) # this is returned as an ndarray

[1 6]


***
# Filtering

#### Boolean Indexing

In [20]:
np2 = np.array([1,2,3,4,5,6,7,8,9])
filt1 = [True, True, False, False, False, False, False, False, False]
print(np2[filt1])

[1 2]


#### Conditional Filtering

In [35]:
even_nums = [True if i%2 == 0 else False for i in np2] #useful list comprehension syntax
print(np2[even_nums])

[2 4 6 8]


#### Numpy Filtering

In [38]:
even_np = np2 % 2 == 0 #note the difference in equal signs
print(even_np)
print(np2[even_np])

[False  True False  True False  True False  True False]
[2 4 6 8]


Fundamentally, `numpy`'s filtering system is based on Boolean Indexing